import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { sizes } from "../styles/theme";
import MobileMainTemplate from "../components/Templates/MobileMainTemplate";
import PcMainTemplate from "../components/Templates/PcMainTemplate";
import useWindowDimensions from "../utils/Hooks/useWindowDimensions";

const Home: NextPage = () => {
  console.log(sizes.laptop.slice(0, -2));
  const { width } = useWindowDimensions();
  console.log(width);
  return (
    <div style={{ height: "1000px" }}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ display: "fixed" }}>
        <h1>Chachi</h1>
        <span>contact link</span>
      </header>
      <main>
        <div style={{ border: "1px solid black", height: "100px" }}>
          photo slider
        </div>
        <div style={{ border: "1px solid black", height: "100px" }}>
          resume list
        </div>
        <div style={{ border: "1px solid black", height: "100px" }}>
          photo slider 2 - measurment
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
