import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { sizes} from "../styles/theme";
import MobileMain from "../components/Templates/MobileMain";
import PcMain from "../components/Templates/PcMain";
import useWindowDimensions from "../utils/Hooks/useWindowDimensions";

const Home: NextPage = () => {
    console.log((sizes.laptop.slice(0,-2)))
    const {width} = useWindowDimensions();
    console.log(width)
  return (
    <div >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          <h1>123</h1>
          {/*{ window.innerWidth < Number(sizes.laptop.slice(0,-2)) ? <MobileMain/> : <PcMain/>}*/}
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
